org: vimalmenon
app: api-krishivmenon
service: api-krishivmenon
frameworkVersion: '3'

plugins:
  - serverless-offline
  - serverless-plugin-typescript

custom:
  serverless-offline:
    httpPort: 5000

provider:
  name: aws
  runtime: nodejs16.x

functions:
  hello:
    handler: services/handler.hello
    events:
      - http:
          path: /
          method: get
